### ISSUE TITLE
Threading error: NoneType object is not callable

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#167]
Minor UI annoyance. Unsure on how to handle those.

    Exception in thread Thread-1 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
      File "/usr/lib/python2.7/threading.py", line 763, in run
      File "/opt/vdirsyncer_env/lib/python2.7/site-packages/vdirsyncer/cli/utils.py", line 475, in worker
      File "/opt/vdirsyncer_env/lib/python2.7/site-packages/vdirsyncer/cli/utils.py", line 460, in _process_job
      File "/usr/lib/python2.7/Queue.py", line 168, in get
      File "/usr/lib/python2.7/threading.py", line 333, in wait
    <type 'exceptions.TypeError'>: 'NoneType' object is not callable

See #166

**Comment by untitaker** [comment]
@flart Can you try again:

    path/to/venv/bin/pip install git+https://github.com/untitaker/vdirsyncer.git

**Comment by flart** [comment]
Sorry, but the exception has only slightly changed:
```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/opt/vdirsyncer_env/lib/python2.7/site-packages/vdirsyncer/cli/utils.py", line 463, in _worker
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
[root@ratte ~]#
```

**Comment by untitaker** [comment]
What about now?

**Comment by flart** [comment]
Seem's to be gone. I tried syncing serveral times (with and without changes) and also discover.

**Comment by untitaker** [comment]
Yay!

**Comment by flart** [comment]
Thank you!
