### ISSUE TITLE
empty lines in config file lead to strange errors

### ISSUE THREAD

**Issue by geier** [untitaker/vdirsyncer#180]
If start_date and end_date are use and the config section contains an empty line I see this error message:

	Syncing home_calendar/work
	Unhandled exception occured for home_calendar/work.
	Traceback (most recent call last):
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/tasks.py", line 72, in sync_collection
	    force_delete=force_delete
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/sync.py", line 158, in sync
	    b_idents = _prepare_idents(storage_b, storage_a, b_href_to_status)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/sync.py", line 113, in _prepare_idents
	    hrefs = _prepare_hrefs(storage, other_storage, href_to_status)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/sync.py", line 98, in _prepare_hrefs
	    for href, etag in storage.list():
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/storage/dav.py", line 633, in list
	    for caldavfilter in caldavfilters:
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/storage/dav.py", line 605, in _get_list_filters
	    start, end):
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/storage/dav.py", line 591, in _get_list_filters
	    start = start.strftime(CALDAV_DT_FORMAT)
	AttributeError: 'unicode' object has no attribute 'strftime'

**Comment by untitaker** [comment]
Ok, could you provide the config for this?

**Comment by untitaker** [comment]
Nevermind, I can reproduce it myself,
