### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by jirib** [untitaker/vdirsyncer#188]
```
$ vdirsyncer -v DEBUG sync
Unhandled exception occured.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/vdirsyncer/cli/__init__.py", line 17, in inner
    f(*a, **kw)
  File "/usr/lib/python2.6/site-packages/vdirsyncer/cli/__init__.py", line 84, in sync
    cli_logger.debug('Using {} maximal workers.'.format(max_workers))
ValueError: zero length field name in format

$ cat ~/.vdirsyncer/config 
[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = ~/.calendar/vdirsyncer/status/

# CALDAV
[pair xxx_calendar]
a = xxx_calendar_local
b = xxx_calendar_remote

[storage xxx_calendar_local]
type = filesystem
path = ~/.calendar/
fileext = .ics

[storage xxx_calendar_remote]
type = caldav
url = http://xxx/home/xxx@xxx.com/Calendar
username = xxx
password = xxx

$ vdirsyncer --version ; python -V
vdirsyncer, version 0.4.3
Python 2.6.6
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
```

**Comment by untitaker** [comment]
Vdirsyncer doesn't support Python 2.6, only 2.7 and 3.3+.
