### ISSUE TITLE
Connection Error - ResponseNotReady with ownCloud

### ISSUE THREAD

**Issue by webworxshop** [untitaker/vdirsyncer#195]
Hi,

I get the following error when trying to use vdirsyncer with my ownCloud account:

```
Traceback (most recent call last):
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/cli/utils.py", line 218, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 303, in discover
    for c in d.discover():
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 166, in discover
    for x in self.find_collections():
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 144, in find_collections
    url = self.find_home()
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 128, in find_home
    url = self.find_principal()
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 119, in find_principal
    data=body)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 237, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/utils/http.py", line 80, in request
    r = func(method, url, **kwargs)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/sessions.py", line 579, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/requests_toolbelt-0.4.0-py2.7.egg/requests_toolbelt/auth/guess.py", line 36, in handle_401
    _r = r.connection.send(prep, **kwargs)
  File "/home/rob/.virtualenvs/vdirsyncer/local/lib/python2.7/site-packages/requests-2.6.2-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ResponseNotReady())
critical: Failed to initialize my_contacts_remote: Internal error, see above.
```

My config is as follows:

```
[general]
status_path = ~/.vdirsyncer/status/
[pair my_contacts]
a = my_contacts_local
b = my_contacts_remote
collections = ["from b"]`

[storage my_contacts_local]
type = filesystem
path = ~/.contacts/
fileext = .vcf`

[storage my_contacts_remote]
type = carddav
url = https://owncloud.myserver.com/remote.php/carddav/
username = xxxx
password = xxxx
verify = false
```

Any help would be very much appreciated.

**Comment by untitaker** [comment]
I am not sure what to do here:

* **Do not use verify = false**. It's a bad default, and I'm considering removing that option in future versions because it's so bad.
* Can you even reach the owncloud instance through the browser?
* A debug log would be apprechiated: `vdirsyncer -vdebug sync`.

**Comment by untitaker** [comment]
To clarify: Use `verify_fingerprint` if your certificate is invalid for some reason.

**Comment by thomwiggers** [comment]
This error might actually be related to something else, I'm getting this message also but when I scroll to the top I see a a different error (see #198) is causing this exception.

**Comment by untitaker** [comment]
Yes, this is the same issue as @thomwiggers posted. @webworxshop The solution is to downgrade to Requests `2.6.0`, e.g. with:

    pip install requests==2.6.0

**Comment by untitaker** [comment]
Requests 2.7 is out, which fixes this.
