### ISSUE TITLE
More verbose error message on empty items returned by DAV server

### ISSUE THREAD

**Issue by birefringence** [untitaker/vdirsyncer#199]
I just had a (very old) eGroupware return an empty item, leading to this error:

    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/cli/tasks.py", line 70, in sync_collection
    force_delete=force_delete
    File "/usr/local/lib/python2.7/dist-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/sync.py", line 159, in sync
    b_info.prepare_idents(storage_a.read_only)
    File "/usr/local/lib/python2.7/dist-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/sync.py", line 114, in prepare_idents
    hrefs_to_download else ()):
    File "/usr/local/lib/python2.7/dist-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/storage/dav.py", line 411, in get_multi
    rv.append((href, Item(raw), etag))
    File "/usr/local/lib/python2.7/dist-packages/vdirsyncer-0.4.4-py2.7.egg/vdirsyncer/utils/vobject.py", line 39, in __init__
    assert isinstance(raw, text_type)

This was difficult to debug, because the error did not contain any information on which item was causing the problem. A more verbose error message would be helpful, e.g. by adding

                raw = raw.text
                if raw is None:
                    dav_logger.warning('Skipping {}, the item content is missing.'
                                       .format(href))
                    continue

to storage/dav.py

**Comment by untitaker** [comment]
I wonder if there is literally an empty item on the server, or eGroupware returned an error? The distinction is important because in case of the former and with your patch applied, `NotFoundError` would be raised for empty items that *should* be downloaded.

Anyway, please try #200.

**Comment by untitaker** [comment]
@birefringence Please try #200 to see whether it provides a better error message in your case, because I'm not sure it's the correct fix:

    pip install --user --upgrade git+https://github.com/untitaker/vdirsyncer.git@handle-empty-items

**Comment by birefringence** [comment]
Yep, it gives an informative error message now. I'm not sure what is the problem with this item on the eGroupware. This item should indeed have content, but the eGroupware does not return any. Other caldav clients cannot synchronize it either.

    warning: Skipping /egroupware/groupdav.php/calendar/e1889acd-d619-47ef-a123-940d18e51b0f.ics, the item content is missing.
    Unhandled exception occured for thomas_calendar.
    Traceback (most recent call last):
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
        force_delete=force_delete
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 163, in sync
        b_info.prepare_idents(storage_a.read_only)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 114, in prepare_idents
        hrefs_to_download else ()):
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 413, in get_multi
        raise exceptions.NotFoundError(href)
    NotFoundError: /egroupware/groupdav.php/calendar/e1889acd-d619-47ef-a123-940d18e51b0f.ics

I had to delete it from the eGroupware to get things back to normal (which was now possible, since before I did not know which one it was).

**Comment by untitaker** [comment]
Alright, but that's not the error message I intended. Please try again, vdirsyncer should now simply download the empty item.

**Comment by birefringence** [comment]
Ok, now I get this:

    Copying (uploading) item e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 to thomas_calendar_local
    Unhandled exception occured for thomas_calendar.
    Traceback (most recent call last):
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
	force_delete=force_delete
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 175, in sync
	action(a_info, b_info, conflict_resolution)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 197, in inner
	dest_href, dest_etag = dest.storage.upload(item)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/storage/base.py", line 17, in inner
	return f(self, *args, **kwargs)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/storage/base.py", line 17, in inner
	return f(self, *args, **kwargs)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 446, in upload
	return self._put(href, item, None)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 429, in _put
	headers=headers
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 237, in request
	return utils.http.request(method, url, session=self._session, **more)
      File "/home/thomas/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 99, in request
	r.raise_for_status()
      File "/home/thomas/.local/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
	raise HTTPError(http_error_msg, response=self)
    HTTPError: 415 Client Error: Unsupported Media Type

(note that the item id changed, because I had to recreate the item on the eGroupware to reproduce the problem).

**Comment by untitaker** [comment]
Hmm, could you re-run this as `vdirsyncer -vdebug sync`?

**Comment by birefringence** [comment]
Ok, done. I've sent the log by GPG encrypted mail.

**Comment by untitaker** [comment]
Are you synchronizing eGroupware with Baikal? In that case you need to delete those items from eGroupware because they are rejected by Baikal when vdirsyncer tries to upload them.

I think vdirsyncer could do a better job at displaying HTTP errors though.

**Comment by birefringence** [comment]
As I already mentioned, deleting the item from the eGroupware was exactly what I did to resolve the problem :-)

Indeed, the error could be handled more gracefully, but I'm happy, since the new error message allows for identifying the item that is causing trouble.

**Comment by untitaker** [comment]
Alright. Please use

    pip install --user --upgrade --force-reinstall git+https://github.com/untitaker/vdirsyncer.git

to install the dev version of vdirsyncer in the future, or just install the latest release (which doesn't contain this UI enhancement yet)

**Comment by birefringence** [comment]
Thanks!
