### ISSUE TITLE
davmail works with evolution but not with vdirsyncer

### ISSUE THREAD

**Issue by kodiakz** [untitaker/vdirsyncer#211]
```
$ vdirsyncer -v DEBUG discover

debug: Using 0 maximal workers.
Discovering collections for pair bob_calendar
debug: GET http://localhost:1080/.well-known/caldav/
debug: {}
debug: None
debug: Sending request...
debug: 503
debug: {'date': 'Tue, 26 May 2015 13:05:40 GMT', 'server': 'squid/3.3.9', 'content-type': 'text/html', 'x-cache': 'MISS from SOMEPROXY:80', 'content-length': '1520', 'mime-version': '1.0', 'x-cache-lookup': 'MISS from SOMEPROXY:80', 'x-squid-error': 'ERR_CONNECT_FAIL 111', 'connection': 'keep-alive'}
debug: b'<html>\n<head>\n  <META HTTP-EQUIV = "Content-Type" CONTENT = "text/html; charset=utf-8" />\n  <META HTTP-EQUIV = "Pragma" \t  CONTENT = "no-cache">\n  <META HTTP-EQUIV = "Expires" \t  CONTENT = "-1">\n  <title>ERROR:The requested URL could not be retrieved</title>\n  <style>\n        body { margin: 0px; background-color:#FFFFFF;}\n        td { font-family: Geneva, Arial, Helvetica, sans-serif;font-size:12px; color:#334163; }\n  </style>\n</head>\n\n<body scroll=\'no\'>\n<table width="100%" height="99%"  border="0"  bgcolor="#FFFFFF">\n    <tr><td></td></tr>\n    <tr>\n        <td height="348" align="left"  background="http://control.antispameurope.de/webfilter/assets/content_background.gif">\n            <form action="webfilter_blocked.php" method="get">\n                <table id = "message" align="center" border="0" width="900">\n                    <tr><td>\n<H1>ERROR</H1>\n<H2>The requested URL could not be retrieved</H2>\n<HR noshade size="1px">\n<P>\nWhile trying to retrieve the URL:\n<A HREF="http://localhost.SOMEDOMAIN:1080/.well-known/caldav/">http://localhost.SOMEDOMAIN:1080/.well-known/caldav/</A>\n<P>\nThe following error was encountered:\n<UL>\n<LI>\n<STRONG>\nConnection to 127.0.0.1 Failed\n</STRONG>\n</UL>\n\n<P>\nThe system returned:\n<PRE><I>    (111) Connection refused</I></PRE>\n\n<P>\nThe remote host or network may be down.  Please try the request again.\n\n                    </td></tr>\n\n                </table>\n            </form>\n        </td>\n    </tr>\n    <tr><td></td></tr>\n</table>\n</body>\n</html>\n'
debug: Server does not support well-known URIs.
debug: PROPFIND http://localhost:1080/users/SOMEUSER@SOMEDOMAIN/calendar/
debug: {'Depth': 0, 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
debug: 
debug:         <d:propfind xmlns:d="DAV:">
debug:             <d:prop>
debug:                 <d:current-user-principal />
debug:             </d:prop>
debug:         </d:propfind>
debug:         
debug: Sending request...
debug: 503
debug: {'date': 'Tue, 26 May 2015 13:05:40 GMT', 'server': 'squid/3.3.9', 'content-type': 'text/html', 'x-cache': 'MISS from SOMEPROXY:80', 'content-length': '1580', 'mime-version': '1.0', 'x-cache-lookup': 'MISS from SOMEPROXY:80', 'x-squid-error': 'ERR_CONNECT_FAIL 111', 'connection': 'keep-alive'}
debug: b'<html>\n<head>\n  <META HTTP-EQUIV = "Content-Type" CONTENT = "text/html; charset=utf-8" />\n  <META HTTP-EQUIV = "Pragma" \t  CONTENT = "no-cache">\n  <META HTTP-EQUIV = "Expires" \t  CONTENT = "-1">\n  <title>ERROR:The requested URL could not be retrieved</title>\n  <style>\n        body { margin: 0px; background-color:#FFFFFF;}\n        td { font-family: Geneva, Arial, Helvetica, sans-serif;font-size:12px; color:#334163; }\n  </style>\n</head>\n\n<body scroll=\'no\'>\n<table width="100%" height="99%"  border="0"  bgcolor="#FFFFFF">\n    <tr><td></td></tr>\n    <tr>\n        <td height="348" align="left"  background="http://control.antispameurope.de/webfilter/assets/content_background.gif">\n            <form action="webfilter_blocked.php" method="get">\n                <table id = "message" align="center" border="0" width="900">\n                    <tr><td>\n<H1>ERROR</H1>\n<H2>The requested URL could not be retrieved</H2>\n<HR noshade size="1px">\n<P>\nWhile trying to retrieve the URL:\n<A HREF="http://SOMEDOMAIN:1080/users/SOMEUSER@SOMEDOMAIN/calendar/">http://localhost.SOMEDOMAIN:1080/users/SOMEUSER@SOMEDOMAIN/calendar/</A>\n<P>\nThe following error was encountered:\n<UL>\n<LI>\n<STRONG>\nConnection to 127.0.0.1 Failed\n</STRONG>\n</UL>\n\n<P>\nThe system returned:\n<PRE><I>    (111) Connection refused</I></PRE>\n\n<P>\nThe remote host or network may be down.  Please try the request again.\n\n                    </td></tr>\n\n                </table>\n            </form>\n        </td>\n    </tr>\n    <tr><td></td></tr>\n</table>\n</body>\n</html>\n'

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/utils.py", line 192, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 302, in discover
    for c in d.discover():
  File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 166, in discover
    for x in self.find_collections():
  File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 144, in find_collections
    url = self.find_home()
  File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 128, in find_home
    url = self.find_principal()
  File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 119, in find_principal
    data=body)
  File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 236, in request
    return utils.request(method, url, session=self._session, **more)
  File "/usr/lib/python3.4/site-packages/vdirsyncer/utils/__init__.py", line 255, in request
    r.raise_for_status()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable

$ cat  .vdirsyncer/config
...
[storage bob_calendar_davmail]
type = caldav
url = http://localhost:1080/users/SOMEMAILADDRESS/calendar/
username = DOMAIN\USERNAME
password = SOMEPASSWORD
```

Accessing the link via browser and evolution works, but not with vdirsyncer (see message above). Something bad with the proxy?

**Comment by untitaker** [comment]
Then I suppose you are missing proxy settings in vdirsyncer that are configured on your desktop (GNOME or else).

**Comment by untitaker** [comment]
@kodiakz Any updates on this?
