### ISSUE TITLE
401 Unauthorized using iCloud

### ISSUE THREAD

**Issue by clauseggers** [untitaker/vdirsyncer#220]
Trying to setup for iCloud, but I'm getting a 401. What am I doing wrong?

(I've changed the tokens in these pastes)
This is my `config`:
```
[general]
status_path = ~/.vdirsyncer/status/

[pair my_contacts]
a = my_contacts_local
b = my_contacts_remote

[storage my_contacts_local]
type = filesystem
path = ~/.contacts/
fileext = .vcf

[storage my_contacts_remote]
type = carddav
url = https://p06-contacts.icloud.com/12345678/principal/ 
username = me@domain.tld
password = mypass
verify_fingerprint = "F5:CC:B1:A7:24:13:36:07:54:8B:00:D8:EB:40:2E:FC:A3:07:6D:58"

[pair my_calendars]
a = my_calendars_local
b = my_calendars_remote

[storage my_calendars_local]
type = filesystem
path = ~/.calendars/
fileext = .ics

[storage my_calendars_remote]
type = caldav
url = https://p06-caldav.icloud.com/12345678/principal/ 
username = me@domain.tld
password = mypass
verify_fingerprint = "F5:CC:B1:A7:24:13:36:07:54:8B:00:D8:EB:40:2E:FC:A3:07:6D:58"
```

And this is the debug output:
```
debug: Using 1 maximal workers.
Detected change in config file, discovering collections for my_contacts
Discovering collections for pair my_contacts
Detected change in config file, discovering collections for my_calendars
Discovering collections for pair my_calendars
Syncing my_contacts
debug: Loaded status for my_contacts
debug: PROPFIND https://p06-contacts.icloud.com/12345678/principal/
debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 1}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
debug: 401
debug: {'x-apple-request-uuid': '0123456-1234-1234-1234-12345678', 'x-apple-jingle-correlation-key': 'ABBBBBBBBBBBBBBBBBBBBB', 'apple-seq': '0', 'www-authenticate': 'X-MobileMe-AuthToken realm="Newcastle", Basic realm="Newcastle"', 'date': 'Thu, 18 Jun 2015 16:49:06 GMT', 'content-length': '0', 'x-responding-instance': 'carddav:123400000:st11p06me-carddav008:1234:15CPlus26:123456', 'apple-tk': 'false', 'strict-transport-security': 'max-age=31536000; includeSubDomains'}
debug: b''
Unhandled exception occured for my_contacts.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 543, in list
    headers=headers)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 305, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/utils/http.py", line 99, in request
    r.raise_for_status()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized
Syncing my_calendars
debug: Loaded status for my_calendars
debug: PROPFIND https://p06-caldav.icloud.com/12345678/principal/
debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': 1}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
debug: 401
debug: {'www-authenticate': 'x-mobileme-authtoken realm="MMCalDav", basic realm="MMCalDav"', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'date': 'Thu, 18 Jun 2015 16:49:06 GMT', 'content-type': 'text/html;charset=utf-8', 'content-length': '141', 'server': 'iCloudCalendarServer 15CPlus26', 'x-responding-server': 'st11p06me-caldav003 8 a1222222222222222222222222', 'x-transaction-id': '0123456-1234-1234-1234-12345678'}
debug: b'<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1><p>You are not authorized to access this resource.</p></body></html>'
Unhandled exception occured for my_calendars.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 668, in list
    for x in DavStorage.list(self):
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 543, in list
    headers=headers)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 305, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/utils/http.py", line 99, in request
    r.raise_for_status()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized
```

**Comment by untitaker** [comment]
Could you try the settings [from the docs](https://vdirsyncer.readthedocs.org/en/stable/supported.html#icloud)?

**Comment by clauseggers** [comment]
Yes. Changing the server ULRs, but keeping the fingerprint I get the exact same output.
Removing the fingerprint so my config is totally similar to the one in the manual gives me another traceback (which was why I tried to change the server URL and fingerprint to begin with):

```
debug: Using 1 maximal workers.
Detected change in config file, discovering collections for my_calendars
Discovering collections for pair my_calendars
Detected change in config file, discovering collections for my_contacts
Discovering collections for pair my_contacts
Syncing my_calendars
debug: Loaded status for my_calendars
debug: PROPFIND https://caldav.icloud.com/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
Unhandled exception occured for my_calendars.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 267, in ssl_wrap_socket
    context.load_verify_locations(ca_certs)
IsADirectoryError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 367, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 269, in ssl_wrap_socket
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 668, in list
    for x in DavStorage.list(self):
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 543, in list
    headers=headers)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 305, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/utils/http.py", line 80, in request
    r = func(method, url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 21] Is a directory
Syncing my_contacts
debug: Loaded status for my_contacts
debug: PROPFIND https://contacts.icloud.com/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
Unhandled exception occured for my_contacts.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 267, in ssl_wrap_socket
    context.load_verify_locations(ca_certs)
IsADirectoryError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 367, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 269, in ssl_wrap_socket
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 543, in list
    headers=headers)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 305, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/me/.local/lib/python3.4/site-packages/vdirsyncer/utils/http.py", line 80, in request
    r = func(method, url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 21] Is a directory
```

**Comment by untitaker** [comment]
Okay, your CA cert setup is broken, but no problem: Just continue using `fingerprint`. But how did you install requests to get to this state?

Are you using something like app-specific passwords for iCloud? I use the normal user password I also use for logging into `icloud.com`.

**Comment by clauseggers** [comment]
Looks like `requests` was pre-installed in the OpenSUSE Tumbleweed distro I'm running. This is the show:
```
Metadata-Version: 1.1
Name: requests
Version: 2.7.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python3.4/site-packages
Requires: 
```
Now is `requests` expected to be in 2.7?

I can login to icloud.com using my normal password, and I took the fingerprint from the certificates on icloud.com.

Previously today I could access iCloud in a browser with one of the URLs (eg. https://p06-contacts.icloud.com or the p01) and I would be presented with a login prompt. Now I don't get that prompt, I just get `Bad request` in my browser. Hmm.

**Comment by untitaker** [comment]
>Now is requests expected to be in 2.7?

This is the version of requests, not the version of Python it is installed under. You did your part well, it is the OpenSUSE maintainers who broke the package. `requests.get('https://google.com')` probably fails in the `python` shell.

The error you recieve with the URLs from the documentation is probably similar, but there are small differences that might be noteworthy.

**Comment by clauseggers** [comment]
>This is the version of requests, not the version of Python it is installed under.

I was referring to `/usr/lib/python3.4/site-packages`. I'm new to Python, but was wondering if some component expected `requests` to be located in `/usr/lib/python2.7/site-packages`. But probably not.

Anyhoot, I'll try removing requests and re-installing it, and if that fails I will try `virtualenv`.

**Comment by untitaker** [comment]
I don't really think it's related to the way you installed vdirsyncer. Could you post the log that occurs when you use the doc's settings? I've encountered a lot of bizarre problems when I used the `p-...`-URL directly.

**Comment by clauseggers** [comment]
When  I use the example in the documentation then I get the output I posted in my second post in this issue.

I have just uninstalled and then re-installed `requests`, and a requests.get works (in both a 2.7 and a 3.4 shell):
```
>>> import requests
>>> requests.get('https://google.com')
<Response [200]>
>>>
```
And running `vdirsyncer` now returns the exact same output as in my second post in this issue, so looks like something else is borked???

**Comment by untitaker** [comment]
>When I use the example in the documentation then I get the output I posted in my second post in this issue.

The *exact* same output? Or is just the error message the same? There are often very minor differences. Could you re-paste (in a [gist](http://gist.github.com/))?

>And running vdirsyncer now returns the exact same output as in my second post in this issue, so looks like something else is borked???

Could you give me `requests.__file__` from the python shell? I need to compare this value with the error message (which might have changed since you've reinstalled requests).

**Comment by clauseggers** [comment]
You are right, there was quite a big difference on the output. Here is the output after I reinstalled the `requests` module: https://gist.github.com/clauseggers/43d1e750b6406585c778

**Comment by untitaker** [comment]
Hmm, actually I don't see any significant difference.

I've found a bug in another DAV client that seems to deal with the same issue: https://github.com/bitfireAT/davdroid/issues/553

Do you have 2-factor-auth enabled?

**Comment by clauseggers** [comment]
The `requests.__file__` outputs:
`'requests/__init__.py'` in `python`, and 
`'/usr/lib/python3.4/site-packages/requests/__init__.py'` in `python3.4`

Yes I do have two factor on. I did wonder if that would work?

**Comment by untitaker** [comment]
Yeah, I think two-factor auth is the... limiting factor here. I suppose you will run into similar problems with other third-party clients.

I don't know if iCloud supports two-factor auth for its CalDAV API. If it does and it's documented somewhere, do send me the documents. But for now you'll probably want to use [app-specific passwords](https://support.apple.com/en-us/HT204397).

**Comment by clauseggers** [comment]
App-specific password: progress (of course, I should have known). I no longer get the python errors, but on the other hand I still don’t get any calendars or contacts. Here is the output: https://gist.github.com/clauseggers/f26b2424c849ec12f287

**Comment by untitaker** [comment]
Hmm, could you try `vdirsyncer -vdebug discover`?

**Comment by clauseggers** [comment]
```
Discovering collections for pair my_calendars
Saved for my_calendars: collections = null
Discovering collections for pair my_contacts
Saved for my_contacts: collections = null
```
Am I doing something wrong here?

**Comment by untitaker** [comment]
Oh, you need this line in your pair section:

    collections = ["from b"]

Otherwise vdirsyncer will assume that the given URL (and the given directory) is directly pointing to a collection.

**Comment by clauseggers** [comment]
Ahh – bingo on that. I remember that I had earlier had a line like that but removed it as it threw an error. Thank you very much for your time – sorry to have spent so much of it on this issue.

**Comment by untitaker** [comment]
No problem, have fun.

**Comment by clauseggers** [comment]
Will do, thanks.
