### ISSUE TITLE
URL containing space are not working anymore

### ISSUE THREAD

**Issue by chris-renner** [untitaker/vdirsyncer#221]
syning caldav server URLs containing space character is causing an exception

```
debug: Normalized URL from '/calendars/__uids__/390421DB-EBF2-4730-8192-CCE3BAE52102/06A5B64D-9216-4217-9FF2-1B295A34F21B/Christi Himmelfahrt-Baden_Wuerttemberg-201305091214226119_schulferien.org.ics' to '/calendars/__uids__/390421DB-EBF2-4730-8192-CCE3BAE52102/06A5B64D-9216-4217-9FF2-1B295A34F21B/Christi%20Himmelfahrt-Baden_Wuerttemberg-201305091214226119_schulferien.org.ics'
Unhandled exception occured for renner/06A5B64D-9216-4217-9FF2-1B295A34F21B.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 162, in sync
    a_info.prepare_idents(storage_b.read_only)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 111, in prepare_idents
    if prefetch else ()):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 387, in get_multi
    raise exceptions.NotFoundError(href)
NotFoundError: /calendars/__uids__/390421DB-EBF2-4730-8192-CCE3BAE52102/06A5B64D-9216-4217-9FF2-1B295A34F21B/Christi Himmelfahrt-Baden_Wuerttemberg-201305091214226119_schulferien.org.ics
```

**Comment by untitaker** [comment]
Hello Chris,

This is not the full log, but I'll need it.

Under which version *did* it work?

**Comment by untitaker** [comment]
Also, which server is this, which vdirsyncer version are you using.

**Comment by chris-renner** [comment]
Hi Markus,

I wanted to reproduce the issue with an older release were the sync was successful.
After installing the older version 0.5.1, I got an exception:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 72, in sync_collection
    a = storage_instance_from_config(config_a)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/utils.py", line 460, in storage_instance_from_config
    cls, new_config = storage_class_from_config(config)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/utils.py", line 446, in storage_class_from_config
    storage_name = config.pop('type')
KeyError: 'type'
```

so I deleted the status folder.
I synced everything completely without any issues. 

After that I upgraded to the latest version 0.5.2 and tried to reproduce the issue. But now everything worked flawlessly.

So everything seems to work now.
Please close the issue.

-- Chris

P.S. I synced filesystem ics against OS X 10.10 Calendar Server

**Comment by untitaker** [comment]
Hmm, I understand why you got the KeyError when downgrading, but the original issue is probably due some serverside change.

**Comment by chris-renner** [comment]
I'm pretty shure that there were no server side changes.
so it seems to be a self-healing computer issue ;-)
