### ISSUE TITLE
Broken sync due to strange UID in calendar

### ISSUE THREAD

**Issue by nblock** [untitaker/vdirsyncer#229]
Hi,
I'm trying to sync the following calender: http://webtermine.at/?ec3_ical into an owncloud 8.1 instance.

Environment:
```
Python 2.7.10
vdirsyncer, version 0.5.2 (virtualenv)
```

Configuration:
```
[pair webtermine]
a = webtermine_upstream
b = webtermine_owncloud
conflict_resolution = a wins

[storage webtermine_upstream]
type = http
url = "https://www.webtermine.at/?ec3_ical"

[storage webtermine_owncloud]
type = caldav
url = "https://myowncloud.example/remote.php/caldav/calendars/external/test"
username = "external"
```

Command and output:
```
$ vdirsyncer -v DEBUG sync webtermine
debug: Using 1 maximal workers.
Syncing webtermine
debug: Loaded status for webtermine
debug: Got password for external from .netrc
debug: GET https://www.webtermine.at/?ec3_ical
debug: {'User-Agent': 'vdirsyncer'}
debug: None
debug: Sending request...
debug: 200
debug: {'content-disposition': 'inline; filename=Webtermineat.ics', 'transfer-encoding': 'chunked', 'set-cookie': 'bb2_screener_=1436455978+185.16.52.227; path=/', 'expires': 'Wed, 11 Jan 1984 05:00:00 GMT', 'server': 'Apache', 'last-modified': 'Thu, 09 Jul 2015 15:32:58 GMT', 'connection': 'close', 'pragma': 'no-cache', 'cache-control': 'no-cache, must-revalidate, max-age=0', 'date': 'Thu, 09 Jul 2015 15:32:57 GMT', 'content-type': 'text/calendar; charset=UTF-8'}
debug: BEGIN:VCALENDAR
debug: VERSION:2.0
debug: X-WR-CALNAME:Webtermine.at
debug: X-WR-TIMEZONE:Europe/Vienna
debug: X-WR-CALDESC:Eine Sammlung von webbezogenen Veranstaltungen in Oesterreich
debug: CALSCALE:GREGORIAN
debug: BEGIN:VEVENT
debug: SUMMARY:ClubComputer cc-Camp&#8217\;15
debug: URL;VALUE=URI:https://www.webtermine.at/2015/clubcomputer-cc-camp15/
debug: UID:1425-https://www.webtermine.at/2015/clubcomputer-cc-camp15/
debug: DESCRIPTION:Das cc-Camp&#8217\;15 ist ein Treffen von NetzenthusiastInnen\,
debug:   Bloggerinnen und Bloggern\, das heuer berteis zum dritten mal in Wien stat
debug:  tfindet. 2014 nahmen über 100 Teilnehmer und Teilnehmerinnen aus unterschie
debug:  dlichsten Lebensbereichen wie Lehrende\, SchülerInnen\, CoderInnen\, IT und
debug:   NetzwerkadministratorInnen\, KünstlerInnen\, PolitikerInnen\, Geschäftsleu
debug:  te an unserem Treffen teil und schufen eine sehr lockere Atmosphäre. Die Te
debug:  ilnahme an der Veranstaltung ist [&hellip\;] Details: https://www.webtermin
debug:  e.at/2015/clubcomputer-cc-camp15/
debug: DTSTART;VALUE=DATE-TIME:20150627T070000Z
debug: DTEND;VALUE=DATE-TIME:20150627T170000Z
debug: LOCATION:HTL Wien 3R\, Rennweg 89b\, 1030 Wien
debug: END:VEVENT
debug: BEGIN:VEVENT
debug: SUMMARY:Castlecamp Kaprun
debug: URL;VALUE=URI:https://www.webtermine.at/2015/castlecamp-kaprun-2/
debug: UID:1447-https://www.webtermine.at/2015/castlecamp-kaprun-2/
debug: DESCRIPTION:Das touristische Barcamp auf der Burg Kaprun. Details: https://
debug:  www.webtermine.at/2015/castlecamp-kaprun-2/
debug: TRANSP:TRANSPARENT
debug: DTSTART;VALUE=DATE:20150904
debug: DTEND;VALUE=DATE:20150907
debug: LOCATION:Burg Kaprun
debug: END:VEVENT
debug: END:VCALENDAR
debug: PROPFIND https://myowncloud.example/remote.php/caldav/calendars/external/test/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
debug: 207
debug: {'content-security-policy': "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *", 'transfer-encoding': 'chunked', 'set-cookie': '5079251d41ae7=s2amr53vqmnjr1spqr3hb86dq5; path=/; secure; HttpOnly', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary': 'Brief,Prefer', 'dav': '1, 3, extended-mkcol, calendar-access, calendar-proxy, access-control, calendarserver-principal-property-search', 'x-sabre-version': '2.1.3', 'server': 'nginx', 'connection': 'keep-alive', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Thu, 09 Jul 2015 15:32:58 GMT', 'content-type': 'application/xml; charset=utf-8'}
debug: <?xml version="1.0" encoding="utf-8"?>
debug: <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/remote.php/caldav/calendars/external/test/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/><cal:calendar/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontenttype/><d:getetag/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
debug: Normalized URL from '/remote.php/caldav/calendars/external/test/' to '/remote.php/caldav/calendars/external/test/'
debug: Skipping '/remote.php/caldav/calendars/external/test/', is collection.
Copying (uploading) item 1447-https://www.webtermine.at/2015/castlecamp-kaprun-2/ to webtermine_owncloud
debug:                                  <script src="/core/js/l10n.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/octemplate.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/eventsource.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/config.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/search/js/search.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/oc-requesttoken.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/apps.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/vendor/snapjs/dist/latest/snap.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/placeholder.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/jquery.avatar.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  <script src="/core/js/avatar.js?v=80d0b3cbaffe3141b5f01d8e7e283b97"></script>
debug:                                  </head>
debug:  <body id="body-login">
debug:          <noscript>
debug:  <div id="nojavascript">
debug:          <div>
debug:                  This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page.          </div>
debug:  </div>
debug: </noscript>
debug:          <div class="wrapper">
debug:                  <div class="v-align">
debug:                                                                  <header role="banner">
debug:                                          <div id="header">
debug:                                                  <div class="logo svg">
debug:                                                          <h1 class="hidden-visually">
debug:                                                                  ownCloud                                                                </h1>
debug:                                                  </div>
debug:                                                  <div id="logo-claim" style="display:none;"></div>
debug:                                          </div>
debug:                                  </header>
debug:                                                                  <ul>
debug:          <li class="error">
debug:                  File not found<br>
debug:                  <p class="hint">The specified document has not been found on the server.</p>
debug:                  <p class="hint"><a href="/index.php">You can click here to return to ownCloud.</a></p>
debug:          </li>
debug:  </ul>
debug:                          <div class="push"></div><!-- for sticky footer -->
debug:                  </div>
debug:          </div>
debug:          <footer role="contentinfo">
debug:                  <p class="info">
debug:                          <a href="https://owncloud.org" target="_blank" rel="noreferrer">ownCloud</a> – web services under your control                  </p>
debug:          </footer>
debug:  </body>
debug: </html>
Unhandled exception occured for webtermine.
Traceback (most recent call last):
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/sync.py", line 175, in sync
    action(a_info, b_info, conflict_resolution)
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/sync.py", line 197, in inner
    dest_href, dest_etag = dest.storage.upload(item)
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 463, in upload
    return self._put(href, item, None)
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 443, in _put
    headers=headers
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 305, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/flo/.virtualenvs/pim-test/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 97, in request
    raise exceptions.NotFoundError(r.reason)
NotFoundError: Not Found
```

From my point of view, the UID of the calendar entry is causing troubles here. Other calendars work just fine.

**Comment by untitaker** [comment]
That's seriously amazing. I'll try to come up with a fix in the next days, it'd be nice if you could notify the host of this calendar that their UIDs are completely wrong.

**Comment by nblock** [comment]
@untitaker Thanks for your quick reply. I'll notify them about the issue.

**Comment by nblock** [comment]
The host changed their UID format and vdirsyncer is working fine now.

**Comment by untitaker** [comment]
vdirsyncer still should be able to deal with this.
