### ISSUE TITLE
TypeError: cafile must be None or a byte string

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#258]
Apparently we can trigger the following by setting `verify` to a string:

    Unhandled exception occured for course1_loc2davical.
    Traceback (most recent call last):
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
        force_delete=force_delete
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 163, in sync
        b_info.prepare_idents(storage_a.read_only)
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
        for href, etag in self.storage.list():
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 760, in list
        for x in DavStorage.list(self):
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 569, in list
        headers=headers)
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 326, in request
        return utils.http.request(method, url, session=self._session, **more)
      File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 79, in request
        r = func(method, url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
        self._validate_conn(conn)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
        conn.connect()
      File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 237, in connect
        ssl_version=resolved_ssl_version)
      File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 263, in ssl_wrap_socket
        ctx.load_verify_locations(ca_certs, None)
      File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 303, in load_verify_locations
        raise TypeError("cafile must be None or a byte string")
    TypeError: cafile must be None or a byte string

See #256 

@rvdse Could you try whether uninstalling `python-openssl` fixes this exception that happens with a quoted cert path?

**Comment by rvdse** [comment]
Yes, it does. It works like it should. And after reinstalling python-openssl (version 0.14-1) the exception appears again.

**Comment by untitaker** [comment]
This might be fixed with https://github.com/pyca/pyopenssl/pull/209, @rvdse ccould you try python-openssl 0.15?

**Comment by rvdse** [comment]
Yes, that fixed it.

I tested using the version on debian unstable, that is python-openssl 0.15.1-2 and I no longer get any errors.

**Comment by untitaker** [comment]
Alright, thanks for the response. I'll close this now as the error is resolved.
