### ISSUE TITLE
PyAsn1Error: TagSet is not asn1Spec: GeneralName()

### ISSUE THREAD

**Issue by sixtyfive** [untitaker/vdirsyncer#260]
Hi, I'm trying to sync my ownCloud's calendar and receive this here:

```
debug: PROPFIND https://mydomain/remote.php/caldav/calendars/me@mydomain/defaultcalendar/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
Unhandled exception occured for my_calendar.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 58, in sync_collection
    force_delete=force_delete
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line 760, in list
    for x in DavStorage.list(self):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line 569, in list
    headers=headers)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line 326, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/utils/http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 244, in connect
    match_hostname(self.sock.getpeercert(),
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 233, in getpeercert
    for value in get_subj_alt_name(x509)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 152, in get_subj_alt_name
    asn1Spec=general_names)
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 55, in valueDecoder
    value, _ = decodeFun(head, asn1Spec, tagSet, length)
  File "/usr/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 798, in __call__
    '%r not in asn1Spec: %r' % (tagSet, asn1Spec)
PyAsn1Error: TagSet(Tag(tagClass=0, tagFormat=0, tagId=6), Tag(tagClass=128, tagFormat=32, tagId=0)) not in asn1Spec: GeneralName()
```

It's the same error message as described at https://github.com/geier/pycarddav/issues/116, not sure though if it's the same problem. Is this anything I'm doing wrong or could it be a bug?

**Comment by untitaker** [comment]
This seems to be a problem with your SSL setup, or in particular, `python-openssl`. Could you try uninstalling it? How well does the site work with curl, wget or a browser?

**Comment by sixtyfive** [comment]
Yes, I think you are right. It works just fine with wget, Firefox or Opera (given that the CACert root cert is installed or by ignoring the certificate check). You made me try verify=false with verify_fingerprint=... now, which works just fine! Thank you! :+1: Have a different problem now, but that's a different issue.

**Comment by untitaker** [comment]
Does uninstalling `python-openssl` change anything? What about doing `pip install pyopenssl` instead of using the Debian package?

**Comment by sixtyfive** [comment]
Indeed, that makes it work, so I guess system `python-openssl` is broken... thank you again!

**Comment by untitaker** [comment]
Do I understand you correctly that doing `pip install pyopenssl` works as well?

**Comment by sixtyfive** [comment]
To be clear, two different things both work:

1. Using `python-openssl` and `verify_fingerprint = SHA1`
2. Using `pip install pyopenssl` instead and then `verify = /path/to/crt`

**Comment by untitaker** [comment]
@sixtyfive Could you provide an example server URL that behaves this way?

**Comment by sixtyfive** [comment]
Tried to reproduce it again, but ever since I installed pyopenssl through `pip`, it is working fine, so closing. Thank you for the help!
