### ISSUE TITLE
vdirsyncer not working with horde server

### ISSUE THREAD

**Issue by sgrbremen** [untitaker/vdirsyncer#264]
I have vdirsyncer 0.5.2 installes on Max OS X (via homebrew) and I am trying to sync calendars between the local file system and our university's Horde server. The auto-discovery of collections seems to work fine, the actual syncing produces only many errors of the type "NotFoundError".

Example:

Unhandled exception occured for sgr_cal/calendar:iU0EldL9ojbyuFBg09A37g8.
Traceback (most recent call last):
  File "/usr/local/Cellar/vdirsyncer/0.5.2/libexec/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/usr/local/Cellar/vdirsyncer/0.5.2/libexec/lib/python2.7/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/usr/local/Cellar/vdirsyncer/0.5.2/libexec/lib/python2.7/site-packages/vdirsyncer/sync.py", line 111, in prepare_idents
    if prefetch else ()):
  File "/usr/local/Cellar/vdirsyncer/0.5.2/libexec/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 387, in get_multi
    raise exceptions.NotFoundError(href)
NotFoundError: /horde3/rpc/calendars/sgr/calendar:iU0EldL9ojbyuFBg09A37g8/qHS4PBwb08G2KnLxo2Qq1w1.ics

What is wrong here? What more info should I provide?

Greetings, Stefan

**Comment by untitaker** [comment]
Please use the `-vdebug` option and wrap with ``` when posting output.

**Comment by sgrbremen** [comment]
Will do, but output will be very long! Should I post everything?

**Comment by untitaker** [comment]
You can also send it to the email address on my profile, that's probably more sensible because the log might contain sensitive information (calendar content).

**Comment by sgrbremen** [comment]
Mail is sent!

**Comment by untitaker** [comment]
Oh, I just noticed that you use version 0.5.2, the latest version 0.6.0 fixes many bugs like this.

**Comment by sgrbremen** [comment]
Ah, 0.6.0 just came around a few hours ago (on homebrew/Mac OS X) - tested it and it worked! Yeah and thanks a lot!

**Comment by untitaker** [comment]
Glad it works!
