### ISSUE TITLE
Exception parsing calendar from webcal.fi

### ISSUE THREAD

**Issue by gregf** [untitaker/vdirsyncer#272]
I get an exception with just about every calendar I have tried from [webcal.fi](http://www.webcal.fi/en-US/manual_subscription.php#holidays)

```
Unhandled exception occured for daylightsavings_calendar.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
    force_delete=force_delete
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/dav.py", line 786, in list
    root = _parse_xml(response.content)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/dav.py", line 76, in _parse_xml
    .format(p.error_log))
InvalidXMLResponse: Invalid XML encountered: <string>:1:1:FATAL:PARSER:ERR_DOCUMENT_EMPTY: Start tag expected, '<' not found
Double-check the URLs in your config.
```

**Comment by untitaker** [comment]
Could you use the `-vdebug` option when reporting such issues? Thanks!

**Comment by untitaker** [comment]
Ah, you have to use the `http` storage type. `caldav` is something else.

**Comment by gregf** [comment]
You were right, switching to http fixed it. Thank you!
