### ISSUE TITLE
Using password-store to get password

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/vdirsyncer#285]
In offlineimap, I have something like that in the config file:

```config
[general]
pythonfile=~/Documents/configuration/scripts/pass_retreive.py

[Repository myserver-remote]
remotepasseval = pass_retreive("myserver-offlineimap")
```

with `pass_retreive.py`:

```python
from subprocess import check_output

def pass_retreive(name):
    # Call the 'pass' command
    output = check_output(["/usr/bin/env", "pass", "show", name])
    # Take 1st line
    return output.split('\n', 1)[0]
```

This works well. How can I do the same with vdirsyncer?

I understand that the password is in plain text in memory for a short amount of time which is a security hole, but I don't care enough and I don't have anything better.

**Comment by untitaker** [comment]
See https://vdirsyncer.readthedocs.org/en/stable/keyring.html

**Comment by DamienCassou** [comment]
Sorry, I forgot to say that I read this already and also https://vdirsyncer.readthedocs.org/en/stable/config.html#general-config. Still, I didn't find enough information. I have the impression that passwordeval is what I need, but I don't know how to use it. An example in the documentation would certainly help.

**Comment by untitaker** [comment]
Yesterday a new version has been released where this feature got overhauled. Could you look again?

On 28 October 2015 05:35:36 CET, Damien Cassou <notifications@github.com> wrote:
>Sorry, I forgot to say that I read this already and also
>https://vdirsyncer.readthedocs.org/en/stable/config.html#general-config.
>Still, I didn't find enough information. I have the impression that
>passwordeval is what I need, but I don't know how to use it. An example
>in the documentation would certainly help.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/285#issuecomment-151718928

-- 
Sent from my phone. Please excuse my brevity.

**Comment by DamienCassou** [comment]
@untitaker thanks for the new release. However, I can't make it work:

```
[storage ...]
password.fetch = ["command", "/usr/bin/env", "pass", "show"]
```

results in

```
$ vdirsyncer sync
Detected change in config file, discovering collections for brique_contacts
Discovering collections for pair brique_contacts
Syncing brique_contacts
Unhandled exception occured for brique_contacts.
Traceback (most recent call last):
  File "vdirsyncer-0.7.0/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 58, in sync_collection
    force_delete=force_delete
  File "vdirsyncer-0.7.0/lib/python2.7/site-packages/vdirsyncer/sync.py", line 168, in sync
    a_info.prepare_idents(storage_b.read_only)
  File "vdirsyncer-0.7.0/lib/python2.7/site-packages/vdirsyncer/sync.py", line 104, in prepare_idents
    for href, etag in self.storage.list():
  File "vdirsyncer-0.7.0/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 565, in list
    headers=headers)
  File "vdirsyncer-0.7.0/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 322, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "vdirsyncer-0.7.0/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "python2.7-requests-2.7.0/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "python2.7-requests-2.7.0/lib/python2.7/site-packages/requests/sessions.py", line 579, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "python2.7-requests-2.7.0/lib/python2.7/site-packages/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/nix/store/03hnsx70m2ayp3ihs8k3047fi70hh03w-python2.7-requests-toolbelt-0.4.0/lib/python2.7/site-packages/requests_toolbelt/auth/guess.py", line 35, in handle_401
    prep = self.auth(prep)
  File "python2.7-requests-2.7.0/lib/python2.7/site-packages/requests/auth.py", line 50, in __call__
    r.headers['Authorization'] = _basic_auth_str(self.username, self.password)
  File "python2.7-requests-2.7.0/lib/python2.7/site-packages/requests/auth.py", line 30, in _basic_auth_str
    b64encode(('%s:%s' % (username, password)).encode('latin1')).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 22: ordinal not in range(128)
```

**Comment by untitaker** [comment]
Are you sure your username contains the character `â`?

**Comment by DamienCassou** [comment]
stupid me, the command must be:

```
password.fetch = ["command", "~/scripts/pass-show-password.sh", "<pass entry>"]
```

with `<pass entry>` being the name of the entry file in password store and `pass-show-password.sh` being

```bash
#!/usr/bin/env bash

/usr/bin/env pass show "$@" | head -n 1
```

**Comment by DamienCassou** [comment]
with above fix, things now work perfectly fine. Thank you very much for 0.7.0 and vdirsyncer.
