### ISSUE TITLE
fail when sync to singlefile

### ISSUE THREAD

**Issue by sotitrox** [untitaker/vdirsyncer#289]
Hello,  I can't sync my owncloud's calendar and contacts to a singlefile in my local sotrage, this is my configuration:

```
[general]
status_path = ~/.vdirsyncer/status/

[pair s_contactos]
a = s_local_contactos
b = s_owncloud_contactos

collections = ["from b"]

metadata = ["displayname"]

[storage s_local_contactos]
type = singlefile
path = ~/Contactos/contactos.vcf

[storage s_owncloud_contactos]
type = carddav
url = LINKTOMYCARDDAV
username =MYUSER
password =MYPASS

# CALDAV
[pair s_calendario]
a = s_local_calendario
b = s_owncloud_calendario
collections = ["from b"]

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage s_local_calendario]
type = singlefile
path = ~/.local/share/orage/orage.ics


[storage s_owncloud_calendario]
type = caldav
url = LINKTOMYCALDAV
username =MYUSER
password =MYPASS
```

and this is the response:

```
$ vdirsyncer -v DEBUG sync
debug: Using 1 maximal workers.
Discovering collections for pair s_calendario

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 210, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 100, in discover
    raise NotImplementedError()
NotImplementedError
critical: Failed to initialize s_local_calendario:
Detected change in config file, discovering collections for s_contactos
Discovering collections for pair s_contactos

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 210, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 100, in discover
    raise NotImplementedError()
NotImplementedError
critical: Failed to initialize s_local_contactos: 
```

**But when I use filesystem storage type works OK, I need a single file.**

**Comment by untitaker** [comment]
Singlefile doesn't support collections, i.e. you can only sync *one* calendar to a file:

* Remove the `collections` param
* Change the URL to the direct URL of the calendar you want to sync (can be found in the ownCloud UI, contains calendar name)

**Comment by sotitrox** [comment]
yeah, now works, thanks
