### ISSUE TITLE
Error when syncing (not with 0.4.2, but with 0.6.0 and later)

### ISSUE THREAD

**Issue by matthiasbeyer** [untitaker/vdirsyncer#290]
I upgraded from 0.4.2 to 0.6.0 and now I get this error message:
I tried with the latest release (not shipped with my distro, yet) and get the same result:

```
error: m_calendar/contact_birthdays: Storage "m_calendar_remote/contact_birthdays" contains multiple items with the same UID or even content. Vdirsyncer will now abort the synchronization of this collection, because the fix for this is not clear; It could be the result of a badly behaving server. You can try running:
error: 
error:     vdirsyncer repair m_calendar_remote/contact_birthdays
error: 
error: But make sure to have a backup of your data in some form. The offending hrefs are:
error: 
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::88.ics'
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics'
```

When running the repair command:

```
warning: This operation will take a very long time.
warning: It's recommended to turn off other client's synchronization features.
Do you want to continue? [y/N]: y
Discovering collections (skipping cache).
Repairing m_calendar_remote/contact_birthdays
warning: Make sure no other program is talking to the server.
[0/2] Processing /oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics
warning: No UID, assigning random one.
Unhandled exception occured.
Traceback (most recent call last):
  File "/nix/store/clkdr59lhhf4psz0x4ivin1vmsy998a0-vdirsyncer-0.7.3/lib/python2.7/site-packages/vdirsyncer/cli/__init__.py", line 45, in inner
    f(*a, **kw)
  File "/nix/store/clkdr59lhhf4psz0x4ivin1vmsy998a0-vdirsyncer-0.7.3/lib/python2.7/site-packages/vdirsyncer/cli/__init__.py", line 238, in repair
    repair_collection(ctx.config, collection)
  File "/nix/store/clkdr59lhhf4psz0x4ivin1vmsy998a0-vdirsyncer-0.7.3/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 102, in repair_collection
    repair_storage(storage)
  File "/nix/store/clkdr59lhhf4psz0x4ivin1vmsy998a0-vdirsyncer-0.7.3/lib/python2.7/site-packages/vdirsyncer/repair.py", line 38, in repair_storage
    assert new_item.uid
AssertionError
```

Can you fix this or at least provide some helpful error message? I'm no python guy, so looking at the source won't help me, ...

**Comment by untitaker** [comment]
Isn't this the same as https://github.com/untitaker/vdirsyncer/issues/281 (where you commented on)?

**Comment by untitaker** [comment]
But yeah, the error message isn't nice.

**Comment by matthiasbeyer** [comment]
naaah, I already reported this. Okay... I'll close this.

Yes, it is the same, though the assertion error looks like the repair command didn't finish (for me as a user it looks this way). Would be nice if this error gets printed in a nice format and vdirsyncer exits "cleanly" (but with bad state, of course). Would be much better user experience!

**Comment by untitaker** [comment]
Latest master should have a better error message, but it isn't going to help you much more than the old one.
