### ISSUE TITLE
Error out nicely when URL is not working

### ISSUE THREAD

**Issue by mbaldessari** [untitaker/vdirsyncer#300]
Noticed the following when trying to sync birthdays from facebook via an outdated URL (url tweaked as it contains sensitive data):
```
Syncing my_fb_birthdays
debug: Loaded status for my_fb_birthdays
debug: GET https://www.facebook.com/ical/b.php?uid=1234&key=123
debug: {'User-Agent': 'vdirsyncer'}
debug: None
debug: Sending request...
debug: Removing latin1 fallback
debug: 200
debug: {'date': 'Sat, 28 Nov 2015 20:01:07 GMT', 'connection': 'keep-alive', 'content-type': 'text/html', 'x-fb-debug': 'bRvdRr8zA63qGdgOjMmL+kIWrBxq5esLAvykehGG7M1M5lqEETqWWs/6tBKz4mBrL8woQlW59YzTanA6iz7c/w==', 'content-length': '55'}
debug: Spiacenti, questo indirizzo non è valido o è scaduto.
Unhandled exception occured for my_fb_birthdays.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 58, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 169, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 104, in prepare_idents
    for href, etag in self.storage.list():
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/http.py", line 149, in list
    for item in split_collection(r.text):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/utils/vobject.py", line 132, in split_collection
    for main in _Component.parse(text, multiple=True):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/utils/vobject.py", line 251, in parse
    stack[-1].props.append(line)
IndexError: list index out of range
```

Might be nice to try and error out a bit more informatively. This happened with 0.7.3

**Comment by untitaker** [comment]
Agreed.

**Comment by untitaker** [comment]
This should be fixed in master. Is it sufficient @mbaldessari?

**Comment by mbaldessari** [comment]
Looking much better, thanks again!

Unhandled exception occured for my_fb_birthdays.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 58, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 169, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 104, in prepare_idents
    for href, etag in self.storage.list():
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/http.py", line 149, in list
    for item in split_collection(r.text):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/utils/vobject.py", line 132, in split_collection
    for main in _Component.parse(text, multiple=True):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/utils/vobject.py", line 255, in parse
    'for more information.'.format(i + 1))
ValueError: Parsing error at line 1. Check the debug log for more information.
