### ISSUE TITLE
Python 2: TypeError: cafile must be None or a byte string

### ISSUE THREAD

**Issue by black2754** [untitaker/vdirsyncer#316]
Hi,

I have an issue with TLS certificate validation and python 2.

In my config file, I have a `verify = ...` line for the remote storage. It references a symlink that points to the actual CA certificate.

If I run `vdirsyncer sync` using python 3.4.3, everything works perfectly.
However, if I use (my default) python 2.7.10, I get the following exception:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/cli/utils.py", line 215, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/storage/dav.py", line 212, in discover
    for c in self.find_collections():
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/storage/dav.py", line 191, in find_collections
    url = self.find_home()
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/storage/dav.py", line 175, in find_home
    url = self.find_principal()
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/storage/dav.py", line 152, in find_principal
    return self.find_principal('')
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/storage/dav.py", line 166, in find_principal
    data=body)
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/storage/dav.py", line 322, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/usr/lib64/python2.7/site-packages/vdirsyncer/utils/http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connection.py", line 250, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 281, in ssl_wrap_socket
    ctx.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/lib64/python2.7/site-packages/OpenSSL/SSL.py", line 303, in load_verify_locations
    raise TypeError("cafile must be None or a byte string")
TypeError: cafile must be None or a byte string
critical: Failed to initialize calendar_remote
critical:   - cafile must be None or a byte string
```

I should probably mention that I am running vdirsyncer 0.7.5 on Gentoo Linux.
Gentoo has a somewhat special python setup that involves wrapper scripts for each application that supports multiple python versions/implementations. I do not think this is related to this issue, but I may be wrong.

**Comment by untitaker** [comment]
I was just beginning to fix this, but TBH I can't be bothered anymore to fix string/encoding bugs on Python 2. Not that one version of Python is inferior to the other in that sense, it's just that supporting two languages with completely different (and contradictory!) string models is too tricky to be worth my time.

This is related to #219. I should probably start working on this issue by noting the ongoing deprecation in the docs. For now I'll leave this open, because with the currently supported versions it *is* a bug. But I don't care.

**Comment by lfam** [comment]
Do you also plan to deprecate Python 2 support in python-atomicwrites and click-log?

**Comment by untitaker** [comment]
No.

Users of it may not have the choice to use a different Python version, but vdirsyncer is not a library.

On 7 January 2016 18:13:37 CET, lfam <notifications@github.com> wrote:
>Do you also plan to deprecate Python 2 support in python-atomicwrites
>and click-log?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/316#issuecomment-169734694

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
@black2754 Am I correct in assuming that everything works with Python 3?

**Comment by black2754** [comment]
Yes, I had no trouble at all using python 3.4.3.

**Comment by untitaker** [comment]
Okay, since I'm going to drop Py2 support anyway in #219 I think I can close this then.
