### ISSUE TITLE
"Failed to import test module" when running the tests

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/vdirsyncer#334]
I face some import test module errors while running the tests:

```
tests.storage.dav.test_caldav (unittest.loader._FailedTest) ... ERROR
tests.storage.dav.test_carddav (unittest.loader._FailedTest) ... ERROR
tests.storage.dav.test_utils (unittest.loader._FailedTest) ... ERROR
tests.storage.test_remotestorage (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests.storage.dav.test_caldav (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests.storage.dav.test_caldav
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/storage/dav/__init__.py", line 16, in <module>
    dav_server = os.environ['DAV_SERVER']
  File "python3-3.4.4/lib/python3.4/os.py", line 635, in __getitem__
    raise KeyError(key) from None
KeyError: 'DAV_SERVER'


======================================================================
ERROR: tests.storage.dav.test_carddav (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests.storage.dav.test_carddav
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/storage/dav/__init__.py", line 16, in <module>
    dav_server = os.environ['DAV_SERVER']
  File "python3-3.4.4/lib/python3.4/os.py", line 635, in __getitem__
    raise KeyError(key) from None
KeyError: 'DAV_SERVER'


======================================================================
ERROR: tests.storage.dav.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests.storage.dav.test_utils
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/storage/dav/__init__.py", line 16, in <module>
    dav_server = os.environ['DAV_SERVER']
  File "python3-3.4.4/lib/python3.4/os.py", line 635, in __getitem__
    raise KeyError(key) from None
KeyError: 'DAV_SERVER'


======================================================================
ERROR: tests.storage.test_remotestorage (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests.storage.test_remotestorage
Traceback (most recent call last):
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/storage/test_remotestorage.py", line 13, in <module>
    remotestorage_server = os.environ['REMOTESTORAGE_SERVER']
  File "python3-3.4.4/lib/python3.4/os.py", line 635, in __getitem__
    raise KeyError(key) from None
KeyError: 'REMOTESTORAGE_SERVER'
```

**Comment by lfam** [comment]
On Wed, Feb 17, 2016 at 06:43:24AM -0800, Damien Cassou wrote:
> I face some import test module errors while running the tests:
> 
> ```
> tests.storage.dav.test_caldav (unittest.loader._FailedTest) ... ERROR
> tests.storage.dav.test_carddav (unittest.loader._FailedTest) ... ERROR
> tests.storage.dav.test_utils (unittest.loader._FailedTest) ... ERROR
> tests.storage.test_remotestorage (unittest.loader._FailedTest) ... ERROR
> 
> ======================================================================
> ERROR: tests.storage.dav.test_caldav (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
>     yield
>   File "python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
>     testMethod()
>   File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
>     raise self._exception
> ImportError: Failed to import test module: tests.storage.dav.test_caldav
> Traceback (most recent call last):
>   File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
>     module = self._get_module_from_name(name)
>   File "python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
>     __import__(name)
>   File "/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/storage/dav/__init__.py", line 16, in <module>
>     dav_server = os.environ['DAV_SERVER']
>   File "python3-3.4.4/lib/python3.4/os.py", line 635, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'DAV_SERVER'

I believe you need a DAV server in your test environment.

**Comment by untitaker** [comment]
Please use `make test` instead of `py.test` directly. Using `py.test` directly used to work, but it lead to inconsistencies and duplicated logic.

Backstory: py.test had a default for DAV_SERVER (and some other variables), and so did the Makefile. Those two defaults eventually diverged, and running `py.test` lead to a different testrun than running `make test`. So I removed the defaults from `py.test` and defined all envvar defaults in the Makefile.

**Comment by DamienCassou** [comment]
@untitaker Thanks. The errors and failures are very different now:

```
==================================== ERRORS ====================================
___________________ ERROR collecting tests/cli/test_main.py ____________________
tests/cli/test_main.py:271: in <module>
    st.characters(
E   AttributeError: 'module' object has no attribute 'characters'
______________________ ERROR at setup of test_request_ssl ______________________
file /tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/utils/test_main.py, line 50
  def test_request_ssl(httpsserver):
        fixture 'httpsserver' not found
        available fixtures: setup_logging, capfd, tmpdir, recwarn, pytestconfig, monkeypatch, no_debug_output, suppress_py2_warning, capsys, benchmark
        use 'py.test --fixtures [testpath]' for help on them.

/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/utils/test_main.py:50
 ERROR at setup of test_request_ssl_fingerprints[94:FD:7A:CB:50:75:A4:69:82:0A:F8:23:DF:07:FC:69:3E:CD:90:CA] 
file /tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/utils/test_main.py, line 69
  @pytest.mark.skipif(_fingerprints_broken(),
                      reason='https://github.com/shazow/urllib3/issues/529')
  @pytest.mark.parametrize('fingerprint', [
      '94:FD:7A:CB:50:75:A4:69:82:0A:F8:23:DF:07:FC:69:3E:CD:90:CA',
      '19:90:F7:23:94:F2:EF:AB:2B:64:2D:57:3D:25:95:2D'
  ])
  def test_request_ssl_fingerprints(httpsserver, fingerprint):
        fixture 'httpsserver' not found
        available fixtures: setup_logging, capfd, tmpdir, recwarn, pytestconfig, monkeypatch, no_debug_output, suppress_py2_warning, capsys, benchmark
        use 'py.test --fixtures [testpath]' for help on them.

/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/utils/test_main.py:69
 ERROR at setup of test_request_ssl_fingerprints[19:90:F7:23:94:F2:EF:AB:2B:64:2D:57:3D:25:95:2D] 
file /tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/utils/test_main.py, line 69
  @pytest.mark.skipif(_fingerprints_broken(),
                      reason='https://github.com/shazow/urllib3/issues/529')
  @pytest.mark.parametrize('fingerprint', [
      '94:FD:7A:CB:50:75:A4:69:82:0A:F8:23:DF:07:FC:69:3E:CD:90:CA',
      '19:90:F7:23:94:F2:EF:AB:2B:64:2D:57:3D:25:95:2D'
  ])
  def test_request_ssl_fingerprints(httpsserver, fingerprint):
        fixture 'httpsserver' not found
        available fixtures: setup_logging, capfd, tmpdir, recwarn, pytestconfig, monkeypatch, no_debug_output, suppress_py2_warning, capsys, benchmark
        use 'py.test --fixtures [testpath]' for help on them.

/tmp/nix-build-vdirsyncer-0.9.0.drv-0/vdirsyncer-0.9.0/tests/utils/test_main.py:69
=================================== FAILURES ===================================
____________________________ test_discover_command _____________________________

tmpdir = local('/tmp/nix-build-vdirsyncer-0.9.0.drv-0/pytest-nixbld/pytest-0/test_discover_command0')
runner = <conftest._CustomRunner object at 0x7ffff2773fd0>

    def test_discover_command(tmpdir, runner):
        runner.write_with_general(dedent('''
        [storage foo]
        type = filesystem
        path = {0}/foo/
        fileext = .txt
    
        [storage bar]
        type = filesystem
        path = {0}/bar/
        fileext = .txt
    
        [pair foobar]
        a = foo
        b = bar
        collections = ["from a"]
        ''').format(str(tmpdir)))
    
        foo = tmpdir.mkdir('foo')
        bar = tmpdir.mkdir('bar')
    
        for x in 'abc':
            foo.mkdir(x)
            bar.mkdir(x)
        bar.mkdir('d')
    
        result = runner.invoke(['sync'])
>       assert not result.exception
E       assert not TypeError("'str' does not support the buffer interface",)
E        +  where TypeError("'str' does not support the buffer interface",) = <Result TypeError("'str' does not support the buffer interface",)>.exception

tests/cli/test_discover.py:31: AssertionError
________________________ test_get_password_from_command ________________________

tmpdir = local('/tmp/nix-build-vdirsyncer-0.9.0.drv-0/pytest-nixbld/pytest-0/test_get_password_from_command0')
runner = <conftest._CustomRunner object at 0x7ffff276cb00>

    def test_get_password_from_command(tmpdir, runner):
        runner.write_with_general(dedent('''
            [pair foobar]
            a = foo
            b = bar
            collections = ["a", "b", "c"]
    
            [storage foo]
            type = filesystem
            path = {base}/foo/
            fileext.fetch = ["command", "echo", ".txt"]
    
            [storage bar]
            type = filesystem
            path = {base}/bar/
            fileext.fetch = ["prompt", "Fileext for bar"]
        '''.format(base=str(tmpdir))))
    
        foo = tmpdir.ensure('foo', dir=True)
        foo.ensure('a', dir=True)
        foo.ensure('b', dir=True)
        foo.ensure('c', dir=True)
        bar = tmpdir.ensure('bar', dir=True)
        bar.ensure('a', dir=True)
        bar.ensure('b', dir=True)
        bar.ensure('c', dir=True)
    
        result = runner.invoke(['discover'], input='.asdf\n')
>       assert not result.exception
E       assert not TypeError("'str' does not support the buffer interface",)
E        +  where TypeError("'str' does not support the buffer interface",) = <Result TypeError("'str' does not support the buffer interface",)>.exception

tests/cli/test_fetchparams.py:34: AssertionError
__________________________________ test_full ___________________________________

tmpdir = local('/tmp/nix-build-vdirsyncer-0.9.0.drv-0/pytest-nixbld/pytest-0/test_full0')
runner = <conftest._CustomRunner object at 0x7ffff2786f98>

    def test_full(tmpdir, runner):
        runner.write_with_general(dedent('''
            [storage foo]
            type = filesystem
            path = {0}/foo/
            fileext = .txt
            ''').format(str(tmpdir)))
    
        foo = tmpdir.mkdir('foo')
    
        result = runner.invoke(['repair', 'foo'], input='y')
>       assert not result.exception
E       assert not TypeError("'str' does not support the buffer interface",)
E        +  where TypeError("'str' does not support the buffer interface",) = <Result TypeError("'str' does not support the buffer interface",)>.exception

tests/cli/test_repair.py:60: AssertionError
_______________ TestFilesystemStorage.test_specialchars[VEVENT] ________________

self = <tests.storage.test_filesystem.TestFilesystemStorage object at 0x7ffff2792cc0>
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7ffff2792a90>
requires_collections = None
get_storage_args = <function TestFilesystemStorage.get_storage_args.<locals>.inner at 0x7ffff27a41e0>
get_item = <function StorageTests.get_item.<locals>.<lambda> at 0x7ffff27a4158>

    def test_specialchars(self, monkeypatch, requires_collections,
                          get_storage_args, get_item):
        if getattr(self, 'dav_server', '') == 'radicale':
            pytest.skip('Radicale is fundamentally broken.')
    
        monkeypatch.setattr('vdirsyncer.utils.generate_href', lambda x: x)
    
        uid = u'test @ foo \xe4t bar \u0433\u0440\u0430\u0434 \u0441\u0430\u0442\u0430\u043d\u0443'
        collection = 'test @ foo \xe4t bar'
    
>       s = self.storage_class(**get_storage_args(collection=collection))

tests/storage/__init__.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/storage/test_filesystem.py:22: in inner
    rv = self.storage_class.create_collection(**rv)
vdirsyncer/storage/filesystem.py:80: in create_collection
    checkdir(expand_path(path), create=True)
vdirsyncer/utils/__init__.py:121: in checkdir
    if not os.path.isdir(path):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = '/tmp/nix-build-vdirsyncer-0.9.0.drv-0/pytest-nixbld/pytest-0/test_specialchars_VEVENT_0/test @ foo \xe4t bar'

    def isdir(s):
        """Return true if the pathname refers to an existing directory."""
        try:
>           st = os.stat(s)
E           UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 99: ordinal not in range(128)

/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/genericpath.py:42: UnicodeEncodeError
________________ TestFilesystemStorage.test_specialchars[VTODO] ________________

self = <tests.storage.test_filesystem.TestFilesystemStorage object at 0x7ffff0488470>
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7ffff04885c0>
requires_collections = None
get_storage_args = <function TestFilesystemStorage.get_storage_args.<locals>.inner at 0x7ffff2788a60>
get_item = <function StorageTests.get_item.<locals>.<lambda> at 0x7ffff27a40d0>

    def test_specialchars(self, monkeypatch, requires_collections,
                          get_storage_args, get_item):
        if getattr(self, 'dav_server', '') == 'radicale':
            pytest.skip('Radicale is fundamentally broken.')
    
        monkeypatch.setattr('vdirsyncer.utils.generate_href', lambda x: x)
    
        uid = u'test @ foo \xe4t bar \u0433\u0440\u0430\u0434 \u0441\u0430\u0442\u0430\u043d\u0443'
        collection = 'test @ foo \xe4t bar'
    
>       s = self.storage_class(**get_storage_args(collection=collection))

tests/storage/__init__.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/storage/test_filesystem.py:22: in inner
    rv = self.storage_class.create_collection(**rv)
vdirsyncer/storage/filesystem.py:80: in create_collection
    checkdir(expand_path(path), create=True)
vdirsyncer/utils/__init__.py:121: in checkdir
    if not os.path.isdir(path):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = '/tmp/nix-build-vdirsyncer-0.9.0.drv-0/pytest-nixbld/pytest-0/test_specialchars_VTODO_0/test @ foo \xe4t bar'

    def isdir(s):
        """Return true if the pathname refers to an existing directory."""
        try:
>           st = os.stat(s)
E           UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 98: ordinal not in range(128)

/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/genericpath.py:42: UnicodeEncodeError
________________ TestFilesystemStorage.test_specialchars[VCARD] ________________

self = <tests.storage.test_filesystem.TestFilesystemStorage object at 0x7ffff048e470>
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7ffff048e5c0>
requires_collections = None
get_storage_args = <function TestFilesystemStorage.get_storage_args.<locals>.inner at 0x7ffff27a42f0>
get_item = <function StorageTests.get_item.<locals>.<lambda> at 0x7ffff27a4598>

    def test_specialchars(self, monkeypatch, requires_collections,
                          get_storage_args, get_item):
        if getattr(self, 'dav_server', '') == 'radicale':
            pytest.skip('Radicale is fundamentally broken.')
    
        monkeypatch.setattr('vdirsyncer.utils.generate_href', lambda x: x)
    
        uid = u'test @ foo \xe4t bar \u0433\u0440\u0430\u0434 \u0441\u0430\u0442\u0430\u043d\u0443'
        collection = 'test @ foo \xe4t bar'
    
>       s = self.storage_class(**get_storage_args(collection=collection))

tests/storage/__init__.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/storage/test_filesystem.py:22: in inner
    rv = self.storage_class.create_collection(**rv)
vdirsyncer/storage/filesystem.py:80: in create_collection
    checkdir(expand_path(path), create=True)
vdirsyncer/utils/__init__.py:121: in checkdir
    if not os.path.isdir(path):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = '/tmp/nix-build-vdirsyncer-0.9.0.drv-0/pytest-nixbld/pytest-0/test_specialchars_VCARD_0/test @ foo \xe4t bar'

    def isdir(s):
        """Return true if the pathname refers to an existing directory."""
        try:
>           st = os.stat(s)
E           UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 98: ordinal not in range(128)

/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/genericpath.py:42: UnicodeEncodeError
========== 6 failed, 236 passed, 152 skipped, 4 error in 2.20 seconds ==========
```

**Comment by DamienCassou** [comment]
In case you care, here are the dependencies:

- python3-3.4.4
- vdirsyncer-0.9.0
- bootstrapped-pip-8.0.2
- pytest-2.7.3
- py-1.4.31
- setuptools-19.4
- hypothesis-1.14.0
- click-6.2
- click-log-0.1.1
- click-threading-0.1.2
- lxml-3.4.4
- setuptools_scm-1.10.1
- requests-toolbelt-0.6.0
- requests-2.8.1
- atomicwrites-0.1.0

**Comment by untitaker** [comment]
I did reply to this on mobile, but it doesn't seem like that email got handled by GitHub properly.

>UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position

Set `LANG` to a non-C locale (preferrably ending in UTF-8) and some of those problems will vanish.

>AttributeError: 'module' object has no attribute 'characters'

Old hypothesis version. It seems that at least version 3 is required.

>TypeError("'str' does not support the buffer interface",)

I strongly suspect this is due to some outdated dependency. I have no idea which one though. 

>fixture 'httpsserver' not found

`pytest-localserver` is a test dependency. You're missing a lot of them... see the Makefile's `install-test` target.

Overall I don't think adding the testsuite to a packaging build is worth the trouble. A simple invocation of vdirsyncer usually detects all environment-specific problems.

**Comment by lfam** [comment]
Here is a working dependency graph for vdirsyncer 0.9.0, with the actual "graph" structure removed. Some of these are implicit inputs that you might not care to package explicitly. Generated on GNU Guix with `guix graph vdirsyncer` and some Unix text filtering.

vdirsyncer-0.9.0
python-oauthlib-1.0.3
python-setuptools-18.3.1
python-coverage-4.0.3
python-nose-1.3.7
python-mock-1.0.1
python-blinker-1.4
python-cryptography-1.2.2
python-cryptography-vectors-1.2.2
python-hypothesis-2.0.0
python-flake8-2.5.1
python-pep8-1.5.7
python-pyflakes-0.8.1
python-mccabe-0.3.1
python-pytest-2.6.1
python-py-1.4.31
python-pretend-1.0.8
python-pyasn1-0.1.8
python-pyasn1-modules-0.0.8
openssl-1.0.2f
perl-5.22.1
python-cffi-1.4.2
pkg-config-0.29
python-sphinx-1.2.3
python-jinja2-2.8
python-markupsafe-0.23
python-docutils-0.12
python-pygments-2.0.2
libffi-3.2.1
python-pycparser-2.14
python-six-1.10.0
python-enum34-1.0
python-idna-2.0
python-iso8601-0.1.10
python-pyjwt-1.4.0
python-pytest-runner-2.6.2
python-setuptools-scm-1.9.0
python-pytest-localserver-0.3.4
unzip-6.0
bzip2-1.0.6
python-requests-2.8.1
python-pytest-cov-2.2.0
python-wheel-0.26.0
python-jsonschema-2.5.1
python-vcversioner-2.14.0.0
python-werkzeug-0.11.2
python-pytest-subtesthack-0.1.1
python-pytest-xprocess-0.9.1
python-pytest-cache-1.0
python-execnet-1.4.1
python-apipkg-1.4
python-psutil-3.3.0
python-wsgi-intercept-0.10.3
python-httplib2-0.9.1
radicale-1.1.1
python-atomicwrites-0.1.9
python-click-6.2
python-click-log-0.1.3
python-click-threading-0.1.2
python-lxml-3.5.0
libxml2-2.9.3
zlib-1.2.8
libxslt-1.1.28
libgcrypt-1.6.5
libgpg-error-1.21
python-minimal-wrapper-3.4.3
python-minimal-3.4.3
python-requests-toolbelt-0.5.0

**Comment by untitaker** [comment]
I see that the PR is merged, I'll close this for now.

**Comment by DamienCassou** [comment]
Thanks for your help
