### ISSUE TITLE
'ascii' codec can't encode character while running tests

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/vdirsyncer#386]
While running `make DETERMINISTIC_TESTS=true test`:

```
============================= test session starts ==============================
platform linux -- Python 3.4.4 -- py-1.4.31 -- pytest-2.7.3
rootdir: /tmp/nix-build-vdirsyncer-0.9.2.drv-0/vdirsyncer-0.9.2, inifile: setup.cfg
plugins: hypothesis, localserver, subtesthack
collected 430 items

[...]
tests/cli/test_main.py:190: AssertionError
________________________ test_invalid_pairs_as_cli_arg _________________________

tmpdir = local('/tmp/nix-build-vdirsyncer-0.9.2.drv-0/pytest-nixbld/pytest-0/test_invalid_pairs_as_cli_arg0')
runner = <conftest._CustomRunner object at 0x7ffff01269b0>

    def test_invalid_pairs_as_cli_arg(tmpdir, runner):
        runner.write_with_general(dedent('''
        [storage foo]
        type = filesystem
        path = {0}/foo/
        fileext = .txt
    
        [storage bar]
        type = filesystem
        path = {0}/bar/
        fileext = .txt
    
        [pair foobar]
        a = foo
        b = bar
        collections = ["a", "b", "c"]
        ''').format(str(tmpdir)))
    
        for base in ('foo', 'bar'):
            base = tmpdir.mkdir(base)
            for c in 'abc':
                base.mkdir(c)
    
        result = runner.invoke(['sync', 'foobar/d'])
        assert result.exception
>       assert 'pair foobar: collection d not found' in result.output.lower()
E       assert 'pair foobar: collection d not found' in ''
E        +  where '' = <built-in method lower of str object at 0x7ffff7fd6848>()
E        +    where <built-in method lower of str object at 0x7ffff7fd6848> = ''.lower
E        +      where '' = <Result RuntimeError('Click will abort further execution because Python 3 was configured to use ASCII as encoding for ... suitable UTF-8\nlocales were discovered.  This most likely requires resolving\nby reconfiguring the locale system.',)>.output

[...]
tests/storage/__init__.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/storage/test_filesystem.py:22: in inner
    rv = self.storage_class.create_collection(**rv)
vdirsyncer/storage/filesystem.py:81: in create_collection
    checkdir(expand_path(path), create=True)
vdirsyncer/utils/__init__.py:121: in checkdir
    if not os.path.isdir(path):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = '/tmp/nix-build-vdirsyncer-0.9.2.drv-0/pytest-nixbld/pytest-0/test_specialchars_VTODO_0/test @ foo \xe4t bar'

    def isdir(s):
        """Return true if the pathname refers to an existing directory."""
        try:
>           st = os.stat(s)
E           UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 98: ordinal not in range(128)

/nix/store/nd1xb6fkm46in9hp78bmby488m95jd96-python3-3.4.4/lib/python3.4/genericpath.py:42: UnicodeEncodeError
________________ TestFilesystemStorage.test_specialchars[VCARD] ________________

self = <tests.storage.test_filesystem.TestFilesystemStorage object at 0x7ffff0087a58>
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7ffff0087be0>
requires_collections = None
get_storage_args = <function TestFilesystemStorage.get_storage_args.<locals>.inner at 0x7ffff00250d0>
get_item = <function StorageTests.get_item.<locals>.<lambda> at 0x7ffff0025378>

    def test_specialchars(self, monkeypatch, requires_collections,
                          get_storage_args, get_item):
        if getattr(self, 'dav_server', '') == 'radicale':
            pytest.skip('Radicale is fundamentally broken.')
    
        monkeypatch.setattr('vdirsyncer.utils.generate_href', lambda x: x)
    
        uid = u'test @ foo \xe4t bar \u0433\u0440\u0430\u0434 \u0441\u0430\u0442\u0430\u043d\u0443'
        collection = 'test @ foo \xe4t bar'
    
>       s = self.storage_class(**get_storage_args(collection=collection))

tests/storage/__init__.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/storage/test_filesystem.py:22: in inner
    rv = self.storage_class.create_collection(**rv)
vdirsyncer/storage/filesystem.py:81: in create_collection
    checkdir(expand_path(path), create=True)
vdirsyncer/utils/__init__.py:121: in checkdir
    if not os.path.isdir(path):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = '/tmp/nix-build-vdirsyncer-0.9.2.drv-0/pytest-nixbld/pytest-0/test_specialchars_VCARD_0/test @ foo \xe4t bar'

    def isdir(s):
        """Return true if the pathname refers to an existing directory."""
        try:
>           st = os.stat(s)
E           UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 98: ordinal not in range(128)

/nix/store/nd1xb6fkm46in9hp78bmby488m95jd96-python3-3.4.4/lib/python3.4/genericpath.py:42: UnicodeEncodeError
============== 19 failed, 250 passed, 161 skipped in 9.88 seconds ==============
Makefile:31: recipe for target 'test' failed
```

* Your vdirsyncer version: 0.9.2
* Your Python version: 3.4.4
* Your operating system: nixos
* Your config file: none

**Comment by DamienCassou** [comment]
I fixed the problem by adding `glibc locales` as test dependency and by hard coding `LC_ALL = "en_US.utf8"` in the test environment.

**Comment by untitaker** [comment]
Is this worth mentioning in the packaging docs? I thought it's prerequisite for most Python programs that deal with unicode data.

**Comment by DamienCassou** [comment]
Maybe you could just say that an utf-8 locale should be used. I don't know.

**Comment by untitaker** [comment]
Not necessarily UTF-8, but `ASCII` will definetly break most Python programs. If you launch vdirsyncer without such a locale, it will error (via click):

	$ LANG= vdirsyncer
	Traceback (most recent call last):
	  File "/home/untitaker/.local/bin/vdirsyncer", line 9, in <module>
		load_entry_point('vdirsyncer==0.9.2', 'console_scripts', 'vdirsyncer')()
	  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/click/core.py", line 700, in __call__
		return self.main(*args, **kwargs)
	  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/click/core.py", line 655, in main
		raise RuntimeError('Click will abort further execution '
	RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
